version: "3.5"

services:
  elasticsearch:
    build: ./elasticsearch
    image: "elasticsearch:21082018"
    container_name: elasticsearch
    restart: always
    expose:
      - 9200
    volumes:
      - elasticsearch_data:/var/data/elasticsearch
      - elasticsearch_logs:/var/log/elasticsearch
    environment:
      - HOST=0.0.0.0
      - PORT=9200
    networks:
      - elk

  kibana:
    build: ./kibana
    image: "kibana:21082018"
    container_name: kibana
    restart: always
    expose:
      - 5601
    environment:
      - HOST=0.0.0.0
      - PORT=5601
      - ES_HOST=elasticsearch
    links:
      - elasticsearch
    networks:
      - elk

  logstash:
    build: ./logstash
    image: "logstash:21082018"
    container_name: logstash
    restart: always
    expose:
      - 5443
    environment:
      - SUPPORT_SSL=no
      - ES_HOST=elasticsearch
      - ES_PORT=9200
    links:
      - elasticsearch
    networks:
      - elk

  nginx:
    build: ./nginx
    image: "nginx:21082018"
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - FQDN=example.com
      - SUPPORT_SSL=no
      - KIBANA_URL=kibana
      - KIBANA_PORT=5601
      - ACCESS_USER=admin
      - ACCESS_PASSWORD=myPassword
    links:
      - kibana
      - logstash
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch_data:
  elasticsearch_logs:
