version: "3.5"

services:
  filebeat:
    build: ./filebeat
    image: "filebeat:27082018"
    container_name: filebeat
    hostname: filebeat
    restart: always
    volumes:
      - /path/to/logs:/logs
    extra_hosts:
      - "logstash:123.45.67.89"
    networks:
      - elk_beats

networks:
  elk_beats:
    driver: bridge
